export const pageType = { JOB_TITLE: 'JOB_TITLE', COMPANY: 'COMPANY' };
export const tabType = {
  OVERVIEW: 'OVERVIEW',
  TIME_AND_SALARY: 'TIME_AND_SALARY',
  WORK_EXPERIENCE: 'WORK_EXPERIENCE',
  INTERVIEW_EXPERIENCE: 'INTERVIEW_EXPERIENCE',
};
