

export const IMG_HOST = 'https://image.goodjob.life';
export const SITE_NAME = 'GoodJob 好工作評論網';
export const PAGE_NAMES = {
  DEFAULT: 'DEFAULT',
  LANDING_PAGE: 'LANDING_PAGE',
  SHARE: 'SHARE',
  SHARE_INTERVIEW: 'SHARE_INTERVIEW',
  SHARE_WORK: 'SHARE_WORK',
  EXPERIENCE_SEARCH: 'EXPERIENCE_SEARCH',
  EXPERIENCE_DETAIL: 'EXPERIENCE_DETAIL',
  LABOR_RIGHTS_MENU: 'LABOR_RIGHTS_MENU',
  LABOR_RIGHTS_SINGLE: 'LABOR_RIGHTS_SINGLE',
  ABOUT: 'ABOUT',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  USER_TERMS: 'USER_TERMS',
  FAQ: 'FAQ',
  GUIDELINES: 'GUIDELINES',
};
