export const LS_INTERVIEW_FORM_KEY = 'LS_INTERVIEW_FORM_KEY';
export const LS_WORK_EXPERIENCES_FORM_KEY = 'LS_WORK_EXPERIENCES_FORM_KEY';
export const LS_TIME_SALARY_FORM_KEY = 'LS_TIME_SALARY_FORM_KEY';
