
const PIXEL_CONTENT_CATEGORY = {
  TIME_AND_SALARY: 'TIME_AND_SALARY',
  LABOR_RIGHTS: 'LABOR_RIGHTS',
  EXPERIENCES: 'EXPERIENCES',
  EXPERIENCES_SEARCH: 'EXPERIENCES_SEARCH',
  TIME_AND_SALARY_SEARCH: 'TIME_AND_SALARY_SEARCH',
  VISIT_INTERVIEW_FORM: 'VISIT_INTERVIEW_FORM',
  VISIT_WORK_EXPERIENCE_FORM: 'VISIT_WORK_EXPERIENCE_FORM',
  VISIT_TIME_AND_SALARY_FORM: 'VISIT_TIME_AND_SALARY_FORM',
  UPLOAD_TIME_AND_SALARY: 'UPLOAD_TIME_AND_SALARY',
  UPLOAD_WORK_EXPERIENCE: 'UPLOAD_WORK_EXPERIENCE',
  UPLOAD_INTERVIEW_EXPERIENCE: 'UPLOAD_INTERVIEW_EXPERIENCE',
};

export default PIXEL_CONTENT_CATEGORY;
