const PIXEL_CONTENT_CATEGORY = {
  VIEW_LABOR_RIGHT: 'VIEW_LABOR_RIGHT',
  VIEW_EXPERIENCE: 'VIEW_EXPERIENCE',
  SEARCH_EXPERIENCES: 'SEARCH_EXPERIENCES',
  SEARCH_TIME_AND_SALARY: 'SEARCH_TIME_AND_SALARY',
  VISIT_INTERVIEW_FORM: 'VISIT_INTERVIEW_FORM',
  VISIT_WORK_EXPERIENCE_FORM: 'VISIT_WORK_EXPERIENCE_FORM',
  VISIT_TIME_AND_SALARY_FORM: 'VISIT_TIME_AND_SALARY_FORM',
  UPLOAD_TIME_AND_SALARY: 'UPLOAD_TIME_AND_SALARY',
  UPLOAD_WORK_EXPERIENCE: 'UPLOAD_WORK_EXPERIENCE',
  UPLOAD_INTERVIEW_EXPERIENCE: 'UPLOAD_INTERVIEW_EXPERIENCE',
};

export default PIXEL_CONTENT_CATEGORY;
