
const PIXEL_CONTENT_CATEGORY = {
  TIME_AND_SALARY: 'TIME_AND_SALARY',
  LABOR_RIGHTS: 'LABOR_RIGHTS',
  EXPERIENCES: 'EXPERIENCES',
  EXPERIENCES_SEARCH: 'EXPERIENCES_SEARCH',
  TIME_AND_SALARY_SEARCH: 'TIME_AND_SALARY_SEARCH',
};

export default PIXEL_CONTENT_CATEGORY;
