export const ACTION = {
  VIEW_ACTION: 'VIEW_ACTION',
  PREVIEW_ACTION: 'PREVIEW_ACTION',
  DETAIL_VIEW_ACTION: 'DETAIL_VIEW_ACTION',
};

export const CONTENT_TYPE = {
  SALARY_WORK_TIME: 'SALARY_WORK_TIME',
  EXPERIENCE: 'EXPERIENCE',
};
