FROM node:10

COPY . /app

WORKDIR /app

ARG RAZZLE_API_HOST
ARG RAZZLE_CONTENTFUL_API_HOST
ARG RAZZLE_FACEBOOK_APP_ID
ARG RAZZLE_GA_ID
ARG RAZZLE_GTM_ID
ARG RAZZLE_PIXEL_ID
ARG RAZZLE_SENTRY_DSN
ARG RAZZLE_GIT_SHA1

ENV RAZZLE_API_HOST="${RAZZLE_API_HOST}" \
    RAZZLE_CONTENTFUL_API_HOST="${RAZZLE_CONTENTFUL_API_HOST}" \
    RAZZLE_FACEBOOK_APP_ID="${RAZZLE_FACEBOOK_APP_ID}" \
    RAZZLE_GA_ID="$RAZZLE_GA_ID" \
    RAZZLE_GTM_ID="$RAZZLE_GTM_ID" \
    RAZZLE_PIXEL_ID="$RAZZLE_PIXEL_ID" \
    RAZZLE_SENTRY_DSN="$RAZZLE_SENTRY_DSN" \
    RAZZLE_GIT_SHA1="$RAZZLE_GIT_SHA1"

RUN yarn install && yarn run build && yarn cache clean

ENV NODE_ENV=production PORT=3000

EXPOSE 3000

CMD ["npm", "run", "start-production"]
