name: Trigger E2E Tests

on:
  push:
    branches:
      - master
      - dev
      - dev2

jobs:
  call-e2e:
    if: github.repository == 'goodjoblife/GoodJobShare'
    runs-on: ubuntu-latest
    steps:
      - name: trigger frontend-e2e integration-test
        run: |
          curl --user "${{ secrets.DEPLOY_CI_TOKEN }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "goodjobshare-updated"}' \
            https://api.github.com/repos/goodjoblife/frontend-e2e/dispatches
