name: Github Actions CI

on:
  push:
    branches:
      - master
      - dev
      - dev2
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint and Unit test
        run: CI=true npm run test
      - name: Build js
        run: CI=false npm run build

  test-future:
    name: test future node
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--openssl-legacy-provider'
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint and Unit test
        run: CI=true npm run test
      - name: Build js
        run: CI=false npm run build

  build-deploy:
    name: Build & Deploy
    if: github.repository == 'goodjoblife/GoodJobShare' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - branch: master
            image_tag: production-${{ github.sha }}
            compose_file: .github/docker-compose-production.yml
            repo: web-server
          - branch: master
            image_tag: stage
            compose_file: .github/docker-compose-stage.yml
            repo: web-server
            event: goodjobshare-master-published
          - branch: dev
            image_tag: dev
            compose_file: .github/docker-compose-dev.yml
            repo: web-server-dev
            event: goodjobshare-dev-published
          - branch: dev2
            image_tag: dev2
            compose_file: .github/docker-compose-dev.yml
            repo: web-server-dev
            event: goodjobshare-dev2-published
    if: github.ref == format('refs/heads/{0}', matrix.branch)
    env:
      REGISTRY: ghcr.io
      REPO_PATH: goodjoblife/goodjobshare/${{ matrix.repo }}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Tag
        run: |
          docker compose -f ${{ matrix.compose_file }} build
          docker tag goodjobshare ${{ env.REGISTRY }}/${{ env.REPO_PATH }}:${{ matrix.image_tag }}
      - name: Push Image
        run: docker push ${{ env.REGISTRY }}/${{ env.REPO_PATH }}:${{ matrix.image_tag }}
      - name: Repository Dispatch (Deploy)
        # if event is not defined, skip
        if: matrix.event != null
        run: |
          curl -u "${{ github.actor }}:${{ secrets.DEPLOY_CI_TOKEN }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "${{ matrix.event }}"}' \
            https://api.github.com/repos/goodjoblife/goodjob-deploy-ci/dispatches
